mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
  - classpath*:/mybatis/mapper/**/*.xml
  type-handlers-package: com.github.apz.springsample.domain.typehandler
spring:
  datasource:
    # url: jdbc:h2:file:./target/h2db
    # username: sa
    url: jdbc:mariadb://127.0.0.1:3306/test
    username: root
    password: password
  flyway:
    enabled: false