CREATE TABLE ITEM (
	ID INT NOT NULL,
	NAME VARCHAR(256) NOT NULL
);

CREATE TABLE ITEM_DETAIL (
	ID INT NOT NULL,
	DETAIL_ID VARCHAR(8) NOT NULL,
	DETAIL_NAME VARCHAR(256) NOT NULL,
	PRICE INT NOT NULL,
	SALE_START DATE,
	SALE_END DATE
);