INSERT INTO DAY_OF_WEEK (STORE_ID,SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,HOLIDAY) VALUES ('S001','0','1','1','1','1','1','1','0');
INSERT INTO DAY_OF_WEEK (STORE_ID,SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,HOLIDAY) VALUES ('S002','1','0','0','0','0','0','0','1');
INSERT INTO DAY_OF_WEEK (STORE_ID,SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,HOLIDAY) VALUES ('S003','1','0','1','1','1','0','1','1');
INSERT INTO DAY_OF_WEEK (STORE_ID,SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,HOLIDAY) VALUES ('S009','1','1','1','1','1','1','1','1');

INSERT INTO STORE_INFO (STORE_ID,STORE_NAME) VALUES ('S001','日祝日お休み店');
INSERT INTO STORE_INFO (STORE_ID,STORE_NAME) VALUES ('S002','平日お休み店');
INSERT INTO STORE_INFO (STORE_ID,STORE_NAME) VALUES ('S003','月金お休み店');
INSERT INTO STORE_INFO (STORE_ID,STORE_NAME) VALUES ('S004','未登録店');

INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('0');
INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('1');
INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('2');
INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('3');
INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('4');
INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('5');
INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('6');
INSERT INTO DAY_OF_WEEK_CODE_DEF(DAY_OF_WEEK_CODE) VALUES ('7');


